### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 22: ordinal not in range(128)

### ISSUE THREAD

**Issue by ghost** [jayme-github/steam_idle#12]
Just installed from `pip2 install steam_idle`

I think it's the ® char

```
1 games with a total of 5 card drops left:
Process IdleChild-1-[Deadbreed®]:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/nick/.local/lib/python2.7/site-packages/steam_idle/idle.py", line 22, in run
    setproctitle.setproctitle(self.name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 22: ordinal not in range(128)
Sleeping for 2:00:00 till Sat Mar 12 16:39:47 2016
```

**Comment by ghost** [comment]
I get this same error running it from the latest code on git repo. Both steam_idle and steamweb is installed under python2. The timer will not advance and I see no gameplay reported on my steam profile.

**Comment by jayme-github** [comment]
Hi and thanks for the report!
Would you be so kind to test the patch? If it works for you (it does in my tests) I will push a new version to pypi.

**Comment by ghost** [comment]
Bingo, that works perfect. Thanks!!!
