### ISSUE TITLE
Error when pip-install is appear

### ISSUE THREAD

**Issue by mihalt** [jayme-github/steam_idle#15]
Hello! I have this error, when install you lib on Windows 7 through pip install steam_idle

![default](https://user-images.githubusercontent.com/30621622/34909524-75dd3224-f8ab-11e7-879a-0bde9c02e4ab.png)

**Comment by jayme-github** [comment]
This looks like an error during setup of `setproctitle` (https://pypi.python.org/pypi/setproctitle).
To confirm this install setproctitle directly (`pip install setproctitle`). If the error occurs again you may want to report the problem there and/or try another (older) version.
