### ISSUE TITLE
setproctitle error

### ISSUE THREAD

**Issue by ghost** [jayme-github/steam_idle#8]
Unable to import module setproctitle. Solved by `pip2 install setproctitle` - should steamweb require setproctitle to ensure it's installed? Or should this be added to the readme? I'm not sure how this module would be installed normally.

**Comment by jayme-github** [comment]
steamweb does not use setproctitle, only steam_idle does.
I've added setproctitle as requirement in [requirements.txt](https://github.com/jayme-github/steam_idle/blob/master/requirements.txt) but never added something like `pip install -r requirements.txt` to the README.

**Comment by ghost** [comment]
Oh it's because I just downloaded the zip and ran the script directly. I've never used `steam_idle` any other way. Is there a better way? :stuck_out_tongue_winking_eye:

**Comment by jayme-github** [comment]
Your way of installing is pretty okay. You could use git instead but the zip is fine to. I'm planing to push the CLI version to pypi for direkt installation via pip but that would require to split the Qt version into a second repo.
Gonna look into this when I have some spare time.

**Comment by ghost** [comment]
Ah ok, should I re-open?

**Comment by jayme-github** [comment]
No, leave it closed please as the issue is resolved for you. Just wanted to share my thoughts :smile:

**Comment by ghost** [comment]
Sure thing! I think getting this on pypi will be nice. I prefer the terminal version btw, I don't see the need for the Qt version but it's cool you're building it. (just my thoughts :wink: )
